sudo: required
services:
    - docker

before_install:
    - docker build -t debashispoddar/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true debashispoddar/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-650841156155"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY