sudo: required
services:
    - docker

before_install:
    - docker build -t debashispoddar/docker-react -f Dockerfile.dev .

script:
    - docker run debashispoddar/docker-react npm run test -- --coverage